apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-watch-svc-account
  namespace: cluster-watch
  labels:
    app: cluster-watch-notifier
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-watch-notifier-cluster-role
  labels:
    app: cluster-watch-notifier
rules:
- apiGroups:
    - ""
  resources:
    - nodes
    - namespaces
  verbs:
    - list
    - watch
    - get
- apiGroups:
    - machineconfiguration.openshift.io
  resources: 
    - machineconfigpools
    - machineconfigs
  verbs:
    - list
    - watch
    - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-watch-notifier-binding
subjects:
- kind: ServiceAccount
  name: cluster-watch-svc-account
  namespace: cluster-watch
roleRef:
  kind: ClusterRole
  name: cluster-watch-notifier-cluster-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cluster-watch-notifier
  name: cluster-watch-notifier
  namespace: cluster-watch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cluster-watch-notifier
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cluster-watch-notifier
    spec:
      serviceAccountName: cluster-watch-svc-account
      containers:
      - image: cluster-watch-notifier:latest
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: cluster-watch-secret
        ports:
          - containerPort: 8080
            protocol: TCP
        livenessProbe:
          failureThreshold: 2
          httpGet:
            path: /live
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 60
          timeoutSeconds: 5
        name: cluster-watch-notifier
        readinessProbe:
          failureThreshold: 2
          httpGet:
            path: /live
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 5
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 250m
            memory: 100Mi
          requests:
            cpu: 50m
            memory: 50Mi
      terminationGracePeriodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: cluster-watch-notifier
  namespace: cluster-watch
  labels:
    app: cluster-watch-notifier
spec:
  ports:
  - port: 80
  selector:
    app: cluster-watch-notifier